/**
 * Los servicios con página propia (/servicios/x y /en/services/x).
 *
 * Cada entrada alimenta una landing completa: hero, beneficios, qué incluye,
 * pasos, precio y FAQ. Una sola fuente para las dos lenguas — la página en
 * español y la de /en salen de la misma fila.
 */
export type Servicio = {
  slug: string;
  slugEn: string;
  nombre: string;
  name: string;
  /** Título SEO (etiqueta <title>) por idioma. */
  titleEs: string;
  titleEn: string;
  descEs: string;
  descEn: string;
  h1Es: string;
  h1En: string;
  subEs: string;
  subEn: string;
  /** Precio "desde", si aplica. */
  lps?: string;
  usd?: string;
  /** Con qué valor del formulario llega preseleccionado. */
  formServicio: string;
  beneficios: { tEs: string; tEn: string; dEs: string; dEn: string }[];
  incluye: { es: string; en: string }[];
  faq: { qEs: string; qEn: string; aEs: string; aEn: string }[];
};

export const servicios: Servicio[] = [
  {
    slug: 'paginas-web',
    slugEn: 'websites',
    nombre: 'Páginas web',
    name: 'Websites',
    titleEs: 'Diseño de páginas web en Honduras | Kizercode',
    titleEn: 'Website design in Honduras | Kizercode',
    descEs: 'Páginas web profesionales para negocios en Honduras desde L 4,000. Diseño propio, con WhatsApp y mapa, listas en una semana. Precio fijo por escrito.',
    descEn: 'Professional websites for businesses in Honduras from $150. Own design, WhatsApp and map included, ready in a week. Fixed price in writing.',
    h1Es: 'Páginas web que traen clientes, no solo visitas.',
    h1En: 'Websites that bring customers, not just visits.',
    subEs: 'Diseño propio para tu marca, rápida en celular con datos móviles, con botón de WhatsApp y mapa. Lista en más o menos una semana.',
    subEn: 'Own design for your brand, fast on mobile data, with a WhatsApp button and map. Ready in about a week.',
    lps: 'L 4,000',
    usd: '$150',
    formServicio: 'Web Applications',
    beneficios: [
      { tEs: 'Diseño propio, no plantilla', tEn: 'Own design, not a template', dEs: 'Tu página se ve como tu negocio, no como la de otros mil.', dEn: 'Your site looks like your business, not like a thousand others.' },
      { tEs: 'Rápida donde importa', tEn: 'Fast where it matters', dEs: 'Optimizada para celular con datos móviles: así navega tu cliente hondureño.', dEn: 'Optimized for phones on mobile data: that is how your customer browses.' },
      { tEs: 'Hecha para vender', tEn: 'Built to sell', dEs: 'WhatsApp a un toque, mapa, y la información que el cliente busca de primero.', dEn: 'WhatsApp one tap away, a map, and the info customers look for first.' },
      { tEs: 'Google la encuentra', tEn: 'Google finds it', dEs: 'Estructura, velocidad y datos correctos para aparecer cuando te buscan.', dEn: 'Structure, speed and correct data to show up when they search for you.' },
    ],
    incluye: [
      { es: 'Diseño a tu marca y colores', en: 'Design for your brand and colors' },
      { es: 'Botón de WhatsApp y mapa de Google', en: 'WhatsApp button and Google map' },
      { es: 'Optimizada para celular', en: 'Mobile-optimized' },
      { es: 'SEO básico y Google Business conectado', en: 'Basic SEO and Google Business connected' },
      { es: 'Dominio y hosting a tu nombre', en: 'Domain and hosting under your name' },
      { es: '30 días de garantía', en: '30-day warranty' },
    ],
    faq: [
      { qEs: '¿En cuánto tiempo está lista?', qEn: 'How soon is it ready?', aEs: 'Una página sencilla, en 3 días a una semana. Te mostramos el diseño antes de publicar.', aEn: 'A simple site, in 3 days to a week. We show you the design before publishing.' },
      { qEs: '¿Puedo editarla yo después?', qEn: 'Can I edit it myself later?', aEs: 'Sí: si necesitás publicar contenido seguido te dejamos un panel para hacerlo vos mismo.', aEn: 'Yes: if you publish often we set up a panel so you can do it yourself.' },
      { qEs: '¿Qué pasa si ya tengo una página vieja?', qEn: 'What if I already have an old site?', aEs: 'La revisamos gratis y te decimos si conviene modernizarla o empezar de cero. Modernizar sale desde L 6,500.', aEn: 'We review it free and tell you whether to modernize or restart. Modernizing starts at $250.' },
    ],
  },
  {
    slug: 'tiendas-en-linea',
    slugEn: 'ecommerce',
    nombre: 'Tiendas en línea',
    name: 'E-commerce',
    titleEs: 'Tiendas en línea para Honduras | Kizercode',
    titleEn: 'E-commerce websites for Honduras | Kizercode',
    descEs: 'Tienda en línea con catálogo, carrito y pagos desde L 14,500. Panel para subir productos vos mismo y conexión con tu inventario.',
    descEn: 'Online store with catalog, cart and payments from $550. A panel to upload products yourself and inventory connection.',
    h1Es: 'Tu tienda abierta 24/7, sin pagar comisión por venta.',
    h1En: 'Your store open 24/7, with no commission per sale.',
    subEs: 'Catálogo, carrito y pagos, con panel para subir tus productos vos mismo. Conectada a tu inventario si ya usás KizerPOS.',
    subEn: 'Catalog, cart and payments, with a panel to upload products yourself. Connected to your inventory if you already run KizerPOS.',
    lps: 'L 14,500',
    usd: '$550',
    formServicio: 'Online Store',
    beneficios: [
      { tEs: 'Vendés mientras dormís', tEn: 'You sell while you sleep', dEs: 'El catálogo atiende, cobra y registra el pedido sin que estés.', dEn: 'The catalog serves, charges and logs the order without you.' },
      { tEs: 'Sin comisiones de plataforma', tEn: 'No platform fees', dEs: 'La tienda es tuya: no le pagás porcentaje a nadie por cada venta.', dEn: 'The store is yours: no percentage paid to anyone per sale.' },
      { tEs: 'Pagos como se paga aquí', tEn: 'Payments the local way', dEs: 'Tarjeta, transferencia o contra entrega: lo que tu cliente use.', dEn: 'Card, transfer or cash on delivery: whatever your customer uses.' },
      { tEs: 'Inventario conectado', tEn: 'Connected inventory', dEs: 'Si usás KizerPOS, la tienda y el local comparten existencias.', dEn: 'With KizerPOS, the store and the shop share stock.' },
    ],
    incluye: [
      { es: 'Catálogo con fotos, variantes y precios', en: 'Catalog with photos, variants and prices' },
      { es: 'Carrito y proceso de pago', en: 'Cart and checkout' },
      { es: 'Panel para subir productos vos mismo', en: 'Panel to upload products yourself' },
      { es: 'Pedidos por WhatsApp si preferís', en: 'WhatsApp ordering if you prefer' },
      { es: 'Conexión con inventario (KizerPOS)', en: 'Inventory connection (KizerPOS)' },
      { es: '30 días de garantía', en: '30-day warranty' },
    ],
    faq: [
      { qEs: '¿Cómo cobro?', qEn: 'How do I get paid?', aEs: 'Configuramos los métodos que uses: tarjeta, transferencia bancaria local o pago contra entrega.', aEn: 'We set up the methods you use: card, local bank transfer or cash on delivery.' },
      { qEs: '¿Yo puedo subir mis productos?', qEn: 'Can I upload my own products?', aEs: 'Sí, el panel es tuyo: fotos, precios y existencias sin depender de nadie.', aEn: 'Yes, the panel is yours: photos, prices and stock without depending on anyone.' },
      { qEs: '¿Cuánto tarda?', qEn: 'How long does it take?', aEs: 'De una a dos semanas según el tamaño del catálogo.', aEn: 'One to two weeks depending on catalog size.' },
    ],
  },
  {
    slug: 'sistemas-a-la-medida',
    slugEn: 'custom-software',
    nombre: 'Sistemas a la medida',
    name: 'Custom software',
    titleEs: 'Software y sistemas a la medida en Honduras | Kizercode',
    titleEn: 'Custom software development in Honduras | Kizercode',
    descEs: 'Sistemas a la medida para tu negocio desde L 25,000: inventario, facturación, pedidos y reportes. Código a tu nombre y precio fijo por escrito.',
    descEn: 'Custom systems for your business from $950: inventory, billing, orders and reports. Code under your name and fixed price in writing.',
    h1Es: 'Un sistema construido sobre tu proceso real.',
    h1En: 'A system built on your real process.',
    subEs: 'Inventario, facturación, pedidos y aprobaciones funcionando como un solo sistema, con roles para tu equipo y reportes en vivo.',
    subEn: 'Inventory, billing, orders and approvals working as one system, with roles for your team and live reports.',
    lps: 'L 25,000',
    usd: '$950',
    formServicio: 'Business System',
    beneficios: [
      { tEs: 'Sobre tu proceso, no una plantilla', tEn: 'On your process, not a template', dEs: 'Mapeamos cómo trabajás hoy y el sistema calza con eso.', dEn: 'We map how you work today and the system fits that.' },
      { tEs: 'Roles y control', tEn: 'Roles and control', dEs: 'Cada quien ve lo suyo, y todo movimiento queda registrado.', dEn: 'Everyone sees their part, and every action is logged.' },
      { tEs: 'Reportes en vivo', tEn: 'Live reports', dEs: 'Ventas, inventario y cuentas al día sin pedirle el Excel a nadie.', dEn: 'Sales, inventory and accounts up to date without chasing spreadsheets.' },
      { tEs: 'Con el equipo incluido', tEn: 'Hardware included', dEs: 'Terminales, impresoras y lectores instalados en tu local, misma propuesta.', dEn: 'Terminals, printers and scanners installed at your place, same proposal.' },
    ],
    incluye: [
      { es: 'Levantamiento de tu proceso y prototipo aprobado por vos', en: 'Process mapping and a prototype you approve' },
      { es: 'Roles, permisos e historial de todo', en: 'Roles, permissions and full history' },
      { es: 'Reportes en vivo y cierre del día', en: 'Live reports and daily close' },
      { es: 'Migración de tus datos (Excel o sistema viejo)', en: 'Data migration (Excel or legacy system)' },
      { es: 'Capacitación a tu equipo', en: 'Team training' },
      { es: 'Código, base y dominio a tu nombre', en: 'Code, database and domain under your name' },
    ],
    faq: [
      { qEs: '¿Cuánto tarda un sistema?', qEn: 'How long does a system take?', aEs: 'De 3 a 6 semanas según lo que cubra, con demos semanales para que veas avances.', aEn: '3 to 6 weeks depending on scope, with weekly demos so you see progress.' },
      { qEs: '¿Funciona sin internet?', qEn: 'Does it work offline?', aEs: 'Si tu operación lo necesita, sí: nuestros POS funcionan sin conexión y sincronizan al volver.', aEn: 'If your operation needs it, yes: our POS runs offline and syncs when back.' },
      { qEs: '¿Y si después quiero cambios?', qEn: 'What if I want changes later?', aEs: 'Los cambios nuevos se cotizan aparte y vos decidís. El código es tuyo: nunca quedás amarrado.', aEn: 'New changes are quoted separately and you decide. The code is yours: never locked in.' },
    ],
  },
  {
    slug: 'apps-moviles',
    slugEn: 'mobile-apps',
    nombre: 'Apps móviles',
    name: 'Mobile apps',
    titleEs: 'Desarrollo de apps móviles en Honduras | Kizercode',
    titleEn: 'Mobile app development in Honduras | Kizercode',
    descEs: 'Apps para iOS y Android con una sola base de código desde L 37,000, conectadas a tu sistema o tienda y publicadas en las tiendas.',
    descEn: 'iOS and Android apps from one codebase from $1,400, connected to your system or store and published in the app stores.',
    h1Es: 'Tu app en iOS y Android, con una sola base de código.',
    h1En: 'Your app on iOS and Android, from one codebase.',
    subEs: 'Conectada a tu sistema o tienda, publicada en las tiendas y con el mismo responsable que el resto de tu software.',
    subEn: 'Connected to your system or store, published in the app stores, with the same person accountable as the rest of your software.',
    lps: 'L 37,000',
    usd: '$1,400',
    formServicio: 'Mobile Apps',
    beneficios: [
      { tEs: 'Una base, dos plataformas', tEn: 'One codebase, two platforms', dEs: 'iOS y Android del mismo código: la mitad del costo de mantener dos.', dEn: 'iOS and Android from the same code: half the cost of maintaining two.' },
      { tEs: 'Conectada a lo tuyo', tEn: 'Connected to your stack', dEs: 'La app habla con tu sistema, tu tienda o tu inventario. Nada aislado.', dEn: 'The app talks to your system, store or inventory. Nothing isolated.' },
      { tEs: 'Publicada de verdad', tEn: 'Actually published', dEs: 'Nos encargamos de App Store y Google Play hasta que esté disponible.', dEn: 'We handle App Store and Google Play until it is live.' },
      { tEs: 'Notificaciones que venden', tEn: 'Notifications that sell', dEs: 'Avisos y recordatorios directos al teléfono de tu cliente.', dEn: 'Alerts and reminders straight to your customer’s phone.' },
    ],
    incluye: [
      { es: 'Diseño de cada pantalla, aprobado por vos', en: 'Every screen designed and approved by you' },
      { es: 'iOS y Android con una sola base', en: 'iOS and Android from one codebase' },
      { es: 'Conexión con tu sistema o tienda', en: 'Connection to your system or store' },
      { es: 'Publicación en App Store y Google Play', en: 'App Store and Google Play publishing' },
      { es: 'Notificaciones push', en: 'Push notifications' },
      { es: 'Código a tu nombre', en: 'Code under your name' },
    ],
    faq: [
      { qEs: '¿Necesito una app o me alcanza con la web?', qEn: 'Do I need an app or is web enough?', aEs: 'Te lo decimos con franqueza en el diagnóstico: muchas veces una web bien hecha alcanza, y sale más barato.', aEn: 'We tell you frankly in the diagnosis: often a well-built web is enough, and cheaper.' },
      { qEs: '¿Cuánto tarda?', qEn: 'How long does it take?', aEs: 'De 4 a 8 semanas más la revisión de las tiendas, con demos semanales.', aEn: '4 to 8 weeks plus store review, with weekly demos.' },
      { qEs: '¿Las cuentas de las tiendas de quién son?', qEn: 'Whose store accounts are they?', aEs: 'Tuyas. App Store y Google Play quedan a nombre de tu empresa.', aEn: 'Yours. App Store and Google Play stay under your company.' },
    ],
  },
  {
    slug: 'automatizacion-ia',
    slugEn: 'ai-automation',
    nombre: 'Automatización con IA',
    name: 'AI automation',
    titleEs: 'Automatización con IA para negocios en Honduras | Kizercode',
    titleEn: 'AI automation for businesses in Honduras | Kizercode',
    descEs: 'Agentes de IA que atienden y cotizan por WhatsApp 24/7 desde L 8,000, con tus precios reales y todo registrado en tu sistema.',
    descEn: 'AI agents that answer and quote on WhatsApp 24/7 from $300, with your real prices and everything logged in your system.',
    h1Es: 'Una IA que atiende, cotiza y nunca se cansa.',
    h1En: 'An AI that answers, quotes and never gets tired.',
    subEs: 'Responde en WhatsApp con tus precios y catálogo reales, registra cada consulta en tu sistema y te pasa el cliente cuando hace falta un humano.',
    subEn: 'It replies on WhatsApp with your real prices and catalog, logs every inquiry in your system and hands over to a human when needed.',
    lps: 'L 8,000',
    usd: '$300',
    formServicio: 'AI Automation',
    beneficios: [
      { tEs: 'Atención 24/7 de verdad', tEn: 'Real 24/7 service', dEs: 'El mensaje de las 11 de la noche se contesta a las 11 de la noche.', dEn: 'The 11 pm message gets answered at 11 pm.' },
      { tEs: 'Con tus datos reales', tEn: 'With your real data', dEs: 'Cotiza con tu lista de precios y tu catálogo, no inventa.', dEn: 'It quotes from your price list and catalog, it does not make things up.' },
      { tEs: 'Todo queda registrado', tEn: 'Everything gets logged', dEs: 'Cada conversación y cotización queda en tu sistema, auditable.', dEn: 'Every conversation and quote lands in your system, auditable.' },
      { tEs: 'Reglas claras', tEn: 'Clear rules', dEs: 'Vos definís qué puede responder sola y cuándo te pasa el cliente.', dEn: 'You define what it answers alone and when it hands over.' },
    ],
    incluye: [
      { es: 'Agente de WhatsApp con tu tono y tus precios', en: 'WhatsApp agent with your tone and prices' },
      { es: 'Cotizaciones automáticas registradas', en: 'Automatic quotes, logged' },
      { es: 'Traspaso a humano cuando hace falta', en: 'Human handover when needed' },
      { es: 'Flujos repetitivos automatizados', en: 'Repetitive workflows automated' },
      { es: 'Reporte de qué pregunta la gente', en: 'Report of what people ask' },
      { es: 'Reglas y límites definidos por vos', en: 'Rules and limits defined by you' },
    ],
    faq: [
      { qEs: '¿La IA va a decir cosas que no son?', qEn: 'Will the AI say wrong things?', aEs: 'Trabaja solo con la información que vos aprobaste, y lo que no sabe lo pasa a un humano. Todo queda auditado.', aEn: 'It only works with information you approved, and hands over what it does not know. Everything is audited.' },
      { qEs: '¿Sirve para mi rubro?', qEn: 'Does it work for my industry?', aEs: 'Si atendés consultas repetidas por WhatsApp (precios, horarios, disponibilidad), sí. Es el caso típico.', aEn: 'If you answer repeated WhatsApp questions (prices, hours, availability), yes. That is the typical case.' },
      { qEs: '¿Cuánto tarda en estar lista?', qEn: 'How long until it is live?', aEs: 'La primera versión, en una a dos semanas con tu catálogo cargado.', aEn: 'The first version, in one to two weeks with your catalog loaded.' },
    ],
  },
  {
    slug: 'crm-a-la-medida',
    slugEn: 'custom-crm',
    nombre: 'CRM a la medida',
    name: 'Custom CRM',
    titleEs: 'CRM a la medida para tu negocio | Kizercode',
    titleEn: 'Custom CRM for your business | Kizercode',
    descEs: 'CRM hecho para tu forma de vender: clientes, seguimientos y cotizaciones en un solo lugar, conectado a WhatsApp. Sin licencias mensuales por usuario.',
    descEn: 'A CRM built for how you sell: customers, follow-ups and quotes in one place, connected to WhatsApp. No monthly per-user licenses.',
    h1Es: 'Todos tus clientes y seguimientos en un solo lugar.',
    h1En: 'All your customers and follow-ups in one place.',
    subEs: 'Quién preguntó, quién cotizó y a quién hay que llamar hoy: un CRM hecho para tu forma de vender, conectado a WhatsApp y sin licencias por usuario.',
    subEn: 'Who asked, who got a quote and who to call today: a CRM built for how you sell, connected to WhatsApp, with no per-user licenses.',
    formServicio: 'Business System',
    beneficios: [
      { tEs: 'Ningún cliente se pierde', tEn: 'No customer falls through', dEs: 'Cada consulta entra al CRM con su seguimiento y su recordatorio.', dEn: 'Every inquiry enters the CRM with its follow-up and reminder.' },
      { tEs: 'Conectado a WhatsApp', tEn: 'Connected to WhatsApp', dEs: 'Las conversaciones quedan pegadas a la ficha del cliente.', dEn: 'Conversations stay attached to the customer record.' },
      { tEs: 'Sin licencias por usuario', tEn: 'No per-user licenses', dEs: 'Pagás una vez. Agregar un vendedor no cuesta mensualidad.', dEn: 'Pay once. Adding a salesperson costs no monthly fee.' },
      { tEs: 'Hecho a tu embudo', tEn: 'Built for your funnel', dEs: 'Tus etapas y tus reglas, no las de un software gringo genérico.', dEn: 'Your stages and rules, not a generic foreign tool’s.' },
    ],
    incluye: [
      { es: 'Fichas de clientes con historial completo', en: 'Customer records with full history' },
      { es: 'Etapas de venta a tu medida', en: 'Sales stages built for you' },
      { es: 'Recordatorios de seguimiento', en: 'Follow-up reminders' },
      { es: 'Cotizaciones desde el CRM', en: 'Quotes from inside the CRM' },
      { es: 'Conexión con WhatsApp', en: 'WhatsApp connection' },
      { es: 'Reportes de ventas y conversión', en: 'Sales and conversion reports' },
    ],
    faq: [
      { qEs: '¿En qué se diferencia de un CRM de suscripción?', qEn: 'How is it different from a subscription CRM?', aEs: 'Es tuyo, calza con tu proceso y no pagás por usuario cada mes. A mediano plazo sale más barato.', aEn: 'It is yours, fits your process and has no monthly per-user fee. Cheaper over time.' },
      { qEs: '¿Puedo migrar mis contactos?', qEn: 'Can I migrate my contacts?', aEs: 'Sí: importamos tu Excel, tu agenda o tu CRM anterior.', aEn: 'Yes: we import your spreadsheet, contacts or previous CRM.' },
      { qEs: '¿Cuánto cuesta?', qEn: 'How much does it cost?', aEs: 'Depende de tu embudo; la mayoría cae en el rango de un sistema a la medida (desde L 25,000). Cotización por escrito tras el diagnóstico gratis.', aEn: 'Depends on your funnel; most fall in the custom-system range (from $950). Written quote after the free diagnosis.' },
    ],
  },
  {
    slug: 'diseno-ux-ui',
    slugEn: 'ux-ui-design',
    nombre: 'Diseño UX/UI',
    name: 'UX/UI design',
    titleEs: 'Diseño UX/UI de aplicaciones y sistemas | Kizercode',
    titleEn: 'UX/UI design for apps and systems | Kizercode',
    descEs: 'Diseño de interfaces que la gente entiende a la primera: prototipos navegables de tu app o sistema antes de escribir código.',
    descEn: 'Interface design people understand at first glance: navigable prototypes of your app or system before writing code.',
    h1Es: 'Pantallas que tu equipo entiende a la primera.',
    h1En: 'Screens your team understands at first glance.',
    subEs: 'Prototipo navegable de cada pantalla antes de escribir una línea de código: lo probás, lo corregimos y el desarrollo va sobre seguro.',
    subEn: 'A navigable prototype of every screen before a line of code: you try it, we fix it, and development runs on rails.',
    formServicio: 'Other',
    beneficios: [
      { tEs: 'Probás antes de pagar desarrollo', tEn: 'Try before paying for development', dEs: 'El prototipo navegable se siente como la app real, sin costo de programarla.', dEn: 'The navigable prototype feels like the real app, without coding cost.' },
      { tEs: 'Menos capacitación', tEn: 'Less training needed', dEs: 'Una interfaz clara se aprende sola: tu equipo arranca en días, no meses.', dEn: 'A clear interface teaches itself: your team starts in days, not months.' },
      { tEs: 'Menos errores de captura', tEn: 'Fewer input errors', dEs: 'Formularios y flujos pensados para el que los usa ocho horas al día.', dEn: 'Forms and flows designed for whoever uses them eight hours a day.' },
      { tEs: 'Coherente con tu marca', tEn: 'Consistent with your brand', dEs: 'Colores, tipografía y componentes de un mismo sistema de diseño.', dEn: 'Colors, type and components from one design system.' },
    ],
    incluye: [
      { es: 'Investigación de cómo trabaja tu equipo', en: 'Research on how your team works' },
      { es: 'Prototipo navegable de cada pantalla', en: 'Navigable prototype of every screen' },
      { es: 'Sistema de diseño con tu marca', en: 'A design system with your brand' },
      { es: 'Versión móvil y de escritorio', en: 'Mobile and desktop versions' },
      { es: 'Pruebas con usuarios reales', en: 'Tests with real users' },
      { es: 'Archivos de diseño a tu nombre', en: 'Design files under your name' },
    ],
    faq: [
      { qEs: '¿Esto viene incluido si me hacen el sistema?', qEn: 'Is this included if you build my system?', aEs: 'Sí: todo sistema o app nuestra pasa por prototipo aprobado por vos. Como servicio aparte es para software que ya tenés o que hace otro equipo.', aEn: 'Yes: every system or app of ours goes through a prototype you approve. As a standalone service it is for software you already have or another team builds.' },
      { qEs: '¿Pueden mejorar un sistema feo que ya uso?', qEn: 'Can you improve an ugly system I already use?', aEs: 'Sí. Rediseñamos pantallas de sistemas existentes para que dejen de dar dolores de cabeza.', aEn: 'Yes. We redesign screens of existing systems so they stop causing headaches.' },
      { qEs: '¿Qué entregan?', qEn: 'What do you deliver?', aEs: 'Prototipo navegable, sistema de diseño y archivos editables, todo a tu nombre.', aEn: 'Navigable prototype, design system and editable files, all under your name.' },
    ],
  },
  {
    slug: 'identidad-visual',
    slugEn: 'branding',
    nombre: 'Identidad visual',
    name: 'Branding',
    titleEs: 'Diseño de logo e identidad visual en Honduras | Kizercode',
    titleEn: 'Logo and brand identity design in Honduras | Kizercode',
    descEs: 'Logo, colores y piezas coherentes para tu negocio: una marca que se ve seria en el rótulo, en Facebook y en la factura.',
    descEn: 'Logo, colors and consistent pieces for your business: a brand that looks serious on the sign, on Facebook and on the invoice.',
    h1Es: 'Una marca que se ve seria en todos lados.',
    h1En: 'A brand that looks serious everywhere.',
    subEs: 'Logo, colores, tipografía y piezas listas para usar: rótulo, redes, factura y uniforme contando la misma historia.',
    subEn: 'Logo, colors, typography and ready-to-use pieces: sign, social media, invoice and uniform telling the same story.',
    formServicio: 'Other',
    beneficios: [
      { tEs: 'Te reconocen', tEn: 'People recognize you', dEs: 'El cliente que te vio en Facebook te identifica en el local.', dEn: 'The customer who saw you on Facebook recognizes your shop.' },
      { tEs: 'Todo combina', tEn: 'Everything matches', dEs: 'Un manual sencillo para que cualquier pieza nueva salga bien.', dEn: 'A simple guide so every new piece comes out right.' },
      { tEs: 'Archivos para todo uso', tEn: 'Files for every use', dEs: 'Versiones para imprenta, redes, rótulo y bordado.', dEn: 'Versions for print, social, signage and embroidery.' },
      { tEs: 'Tuyo para siempre', tEn: 'Yours forever', dEs: 'Archivos editables a tu nombre. No dependés de nosotros.', dEn: 'Editable files under your name. You do not depend on us.' },
    ],
    incluye: [
      { es: 'Logo con variantes (color, blanco, negro)', en: 'Logo with variants (color, white, black)' },
      { es: 'Paleta de colores y tipografía', en: 'Color palette and typography' },
      { es: 'Manual de uso sencillo', en: 'A simple usage guide' },
      { es: 'Plantillas para redes sociales', en: 'Social media templates' },
      { es: 'Papelería: factura, tarjeta, firma de correo', en: 'Stationery: invoice, card, email signature' },
      { es: 'Archivos editables a tu nombre', en: 'Editable files under your name' },
    ],
    faq: [
      { qEs: 'Ya tengo logo, ¿me sirve algo de esto?', qEn: 'I already have a logo, is any of this useful?', aEs: 'Sí: ordenamos lo que tenés en un sistema coherente, o lo refrescamos sin perder lo que la gente ya reconoce.', aEn: 'Yes: we organize what you have into a coherent system, or refresh it without losing what people recognize.' },
      { qEs: '¿Cuántas propuestas de logo veo?', qEn: 'How many logo options do I see?', aEs: 'Tres caminos distintos, y afinamos el que elijás hasta que quede.', aEn: 'Three distinct directions, and we refine your pick until it lands.' },
      { qEs: '¿Cuánto tarda?', qEn: 'How long does it take?', aEs: 'De una a dos semanas según cuántas piezas necesités.', aEn: 'One to two weeks depending on how many pieces you need.' },
    ],
  },
  {
    slug: 'seo',
    slugEn: 'seo',
    nombre: 'Posicionamiento (SEO)',
    name: 'SEO',
    titleEs: 'SEO en Honduras: aparecer en Google | Kizercode',
    titleEn: 'SEO in Honduras: show up on Google | Kizercode',
    descEs: 'Posicionamiento en Google para negocios hondureños: estructura, contenido, velocidad y Google Business para aparecer cuando te buscan.',
    descEn: 'Google positioning for Honduran businesses: structure, content, speed and Google Business so you show up when they search.',
    h1Es: 'Que te encuentren cuando te buscan.',
    h1En: 'Be found when they search for you.',
    subEs: 'Estructura, contenido, velocidad y tu ficha de Google Business trabajando juntos para aparecer en Google y en Maps.',
    subEn: 'Structure, content, speed and your Google Business profile working together to show up on Google and Maps.',
    formServicio: 'Other',
    beneficios: [
      { tEs: 'Clientes que ya te buscan', tEn: 'Customers already searching', dEs: 'El que googlea "reparación de computadoras cerca" ya quiere comprar.', dEn: 'Whoever googles "computer repair near me" already wants to buy.' },
      { tEs: 'Maps es la mitad del juego', tEn: 'Maps is half the game', dEs: 'Ficha de Google Business completa, con reseñas y fotos que convencen.', dEn: 'A complete Google Business profile, with convincing reviews and photos.' },
      { tEs: 'Medido, no prometido', tEn: 'Measured, not promised', dEs: 'Ves en qué posición estás y cuánta gente llega, mes a mes.', dEn: 'You see your position and how many people arrive, month by month.' },
      { tEs: 'Sin humo', tEn: 'No smoke', dEs: 'Nadie puede garantizar el #1. Sí podemos garantizar el trabajo que lo hace posible.', dEn: 'No one can guarantee #1. We can guarantee the work that makes it possible.' },
    ],
    incluye: [
      { es: 'Auditoría técnica de tu sitio', en: 'Technical audit of your site' },
      { es: 'Palabras clave de tu rubro y tu zona', en: 'Keywords for your industry and area' },
      { es: 'Contenido que responde lo que buscan', en: 'Content answering what they search' },
      { es: 'Google Business optimizado', en: 'Optimized Google Business' },
      { es: 'Velocidad y datos estructurados', en: 'Speed and structured data' },
      { es: 'Reporte mensual de posiciones', en: 'Monthly ranking report' },
    ],
    faq: [
      { qEs: '¿Cuánto tarda en verse resultado?', qEn: 'How long until results show?', aEs: 'Lo local (Maps) se mueve en semanas; las búsquedas competidas, en 3 a 6 meses. Te mostramos el avance cada mes.', aEn: 'Local (Maps) moves in weeks; competitive searches, 3 to 6 months. We show progress monthly.' },
      { qEs: '¿Me garantizan el primer lugar?', qEn: 'Do you guarantee #1?', aEs: 'No, y desconfiá del que te lo garantice. Garantizamos trabajo medible y reportado.', aEn: 'No, and distrust anyone who guarantees it. We guarantee measurable, reported work.' },
      { qEs: '¿Sirve si no tengo página?', qEn: 'Useful without a website?', aEs: 'Google Business solo ya trae clientes locales. Pero página + ficha es lo que de verdad rinde.', aEn: 'Google Business alone brings local customers. But site + profile is what truly performs.' },
    ],
  },
  {
    slug: 'anuncios',
    slugEn: 'ads',
    nombre: 'Anuncios y captación',
    name: 'Ads and acquisition',
    titleEs: 'Publicidad en Google y Meta para Honduras | Kizercode',
    titleEn: 'Google and Meta ads for Honduras | Kizercode',
    descEs: 'Campañas en Google y Facebook/Instagram con seguimiento real: sabés cuánto costó traer cada cliente. Reporte semanal.',
    descEn: 'Google and Facebook/Instagram campaigns with real tracking: you know what each customer cost. Weekly report.',
    h1Es: 'Publicidad que se mide en clientes, no en likes.',
    h1En: 'Advertising measured in customers, not likes.',
    subEs: 'Campañas en Google y Meta con el presupuesto puesto donde deja clientes, seguimiento de cada contacto y reporte semanal.',
    subEn: 'Google and Meta campaigns with the budget where it brings customers, tracking on every contact and a weekly report.',
    formServicio: 'Other',
    beneficios: [
      { tEs: 'Sabés qué funciona', tEn: 'You know what works', dEs: 'Cada peso invertido se rastrea hasta el mensaje o la llamada que generó.', dEn: 'Every unit spent is tracked to the message or call it generated.' },
      { tEs: 'Presupuesto cuidado', tEn: 'Budget looked after', dEs: 'Lo que no rinde se apaga; lo que rinde recibe más. Cada semana.', dEn: 'What underperforms gets turned off; what performs gets more. Weekly.' },
      { tEs: 'Aterrizan bien', tEn: 'They land well', dEs: 'El anuncio lleva a una página hecha para convertir, no a un perfil frío.', dEn: 'Ads lead to a page built to convert, not a cold profile.' },
      { tEs: 'Tu cuenta, tu píxel', tEn: 'Your account, your pixel', dEs: 'Las cuentas publicitarias quedan a tu nombre, con su historial.', dEn: 'Ad accounts stay under your name, with their history.' },
    ],
    incluye: [
      { es: 'Campañas en Google y/o Meta', en: 'Google and/or Meta campaigns' },
      { es: 'Píxel y conversiones bien medidas', en: 'Pixel and conversions measured right' },
      { es: 'Diseño de anuncios', en: 'Ad creatives' },
      { es: 'Página de aterrizaje que convierte', en: 'A landing page that converts' },
      { es: 'Optimización semanal', en: 'Weekly optimization' },
      { es: 'Reporte semanal en cristiano', en: 'A weekly report in plain words' },
    ],
    faq: [
      { qEs: '¿Cuánto presupuesto necesito?', qEn: 'How much budget do I need?', aEs: 'Se puede empezar con poco (L 3,000–5,000/mes de pauta) y escalar cuando los números lo justifiquen.', aEn: 'You can start small ($120–200/month in spend) and scale when the numbers justify it.' },
      { qEs: '¿El presupuesto de pauta va aparte?', qEn: 'Is ad spend separate?', aEs: 'Sí: la pauta se la pagás directo a Google/Meta desde tu cuenta. Nuestro fee es por la gestión.', aEn: 'Yes: spend goes straight to Google/Meta from your account. Our fee is for management.' },
      { qEs: '¿En cuánto tiempo veo clientes?', qEn: 'How soon do I see customers?', aEs: 'Los primeros contactos suelen llegar la primera semana; optimizar el costo por cliente toma un mes.', aEn: 'First contacts usually arrive within a week; optimizing cost per customer takes a month.' },
    ],
  },
  {
    slug: 'redes-sociales',
    slugEn: 'social-media',
    nombre: 'Redes sociales',
    name: 'Social media',
    titleEs: 'Manejo de redes sociales para negocios | Kizercode',
    titleEn: 'Social media management for businesses | Kizercode',
    descEs: 'Manejo de Facebook e Instagram con contenido de tu negocio real, respuestas a tiempo y piezas con tu marca.',
    descEn: 'Facebook and Instagram management with content from your real business, timely replies and on-brand pieces.',
    h1Es: 'Redes activas sin que vos tengás que estar posteando.',
    h1En: 'Active social media without you having to post.',
    subEs: 'Contenido de tu negocio real, piezas con tu marca, publicación constante y respuestas a tiempo en Facebook e Instagram.',
    subEn: 'Content from your real business, on-brand pieces, consistent posting and timely replies on Facebook and Instagram.',
    formServicio: 'Other',
    beneficios: [
      { tEs: 'Constancia sin esfuerzo tuyo', tEn: 'Consistency without your effort', dEs: 'Calendario mensual: tus redes publican aunque vos estés vendiendo.', dEn: 'A monthly calendar: your accounts post while you sell.' },
      { tEs: 'Contenido de tu negocio real', tEn: 'Content from your real business', dEs: 'Tus productos y tu gente, no plantillas de banco de imágenes.', dEn: 'Your products and your people, not stock templates.' },
      { tEs: 'Respuestas a tiempo', tEn: 'Timely replies', dEs: 'Los comentarios y mensajes se contestan, que ahí también se vende.', dEn: 'Comments and messages get answered — sales happen there too.' },
      { tEs: 'Con tu marca', tEn: 'On-brand', dEs: 'Cada pieza usa tus colores y tu voz. Coherente con tu página.', dEn: 'Every piece uses your colors and voice. Consistent with your site.' },
    ],
    incluye: [
      { es: 'Calendario de contenido mensual', en: 'Monthly content calendar' },
      { es: 'Diseño de piezas con tu marca', en: 'On-brand piece design' },
      { es: 'Publicación en Facebook e Instagram', en: 'Posting on Facebook and Instagram' },
      { es: 'Respuesta a comentarios y mensajes', en: 'Replies to comments and messages' },
      { es: 'Reporte mensual de alcance', en: 'Monthly reach report' },
      { es: 'Coordinación con tus promociones', en: 'Coordination with your promos' },
    ],
    faq: [
      { qEs: '¿Ustedes responden los mensajes?', qEn: 'Do you answer messages?', aEs: 'Los comunes sí, con guías que armamos con vos. Lo delicado te lo pasamos de una.', aEn: 'Common ones yes, with playbooks we build with you. Sensitive ones go straight to you.' },
      { qEs: '¿Necesito salir en las fotos?', qEn: 'Do I need to appear in photos?', aEs: 'Ayuda muchísimo: la gente le compra a gente. Pero armamos el plan con lo que estés cómodo.', aEn: 'It helps a lot: people buy from people. But we plan around what you are comfortable with.' },
      { qEs: '¿Esto es mensual?', qEn: 'Is this monthly?', aEs: 'Sí, es de los servicios que van en plan mensual. Cotización según cuántas redes y piezas.', aEn: 'Yes, this one runs as a monthly plan. Quoted by networks and volume.' },
    ],
  },
  {
    slug: 'modernizacion-web',
    slugEn: 'website-redesign',
    nombre: 'Modernizar tu sitio',
    name: 'Website redesign',
    titleEs: 'Modernizar tu página web vieja | Kizercode',
    titleEn: 'Redesign your old website | Kizercode',
    descEs: 'Rediseño de sitios viejos desde L 6,500: diseño de hoy, IA y WhatsApp, sin perder tu contenido ni tu dominio.',
    descEn: 'Old-website redesign from $250: today’s design, AI and WhatsApp, without losing your content or domain.',
    h1Es: 'Tu misma página, pero de este año.',
    h1En: 'Your same website, but from this year.',
    subEs: 'Diseño de hoy sin empezar de cero: aprovechamos tu contenido y tu dominio, y le metemos WhatsApp, IA y lo que le falte.',
    subEn: 'Today’s design without starting from zero: we keep your content and domain, and add WhatsApp, AI and whatever is missing.',
    lps: 'L 6,500',
    usd: '$250',
    formServicio: 'Site Modernization',
    beneficios: [
      { tEs: 'Sin empezar de cero', tEn: 'No starting from zero', dEs: 'Tu contenido, tus fotos y tu dominio se quedan. Cambia lo que se ve.', dEn: 'Your content, photos and domain stay. What changes is the look.' },
      { tEs: 'Google lo premia', tEn: 'Google rewards it', dEs: 'Velocidad y estructura nuevas: un sitio moderno posiciona mejor.', dEn: 'New speed and structure: a modern site ranks better.' },
      { tEs: 'Deja de espantar', tEn: 'Stops scaring people off', dEs: 'Un sitio de 2015 le dice al cliente que quizás ya ni existís.', dEn: 'A 2015 site tells customers you might not even exist anymore.' },
      { tEs: 'Con lo de hoy', tEn: 'With today’s tools', dEs: 'WhatsApp, mapa, IA si aplica, y medición de visitas de verdad.', dEn: 'WhatsApp, map, AI where it fits, and real visit measurement.' },
    ],
    incluye: [
      { es: 'Revisión gratis de tu sitio actual', en: 'Free review of your current site' },
      { es: 'Rediseño completo con tu contenido', en: 'Full redesign keeping your content' },
      { es: 'WhatsApp, mapa y medición', en: 'WhatsApp, map and measurement' },
      { es: 'Velocidad y SEO al día', en: 'Speed and SEO up to date' },
      { es: 'Tu dominio se queda igual', en: 'Your domain stays the same' },
      { es: '30 días de garantía', en: '30-day warranty' },
    ],
    faq: [
      { qEs: '¿Pierdo mi posición en Google?', qEn: 'Do I lose my Google ranking?', aEs: 'No: migramos con redirecciones correctas y normalmente la posición mejora por la velocidad nueva.', aEn: 'No: we migrate with proper redirects and rankings usually improve thanks to the new speed.' },
      { qEs: '¿Y si mi página está en Wix/WordPress?', qEn: 'What if my site is on Wix/WordPress?', aEs: 'Da igual dónde esté: rescatamos el contenido y lo montamos moderno.', aEn: 'Wherever it lives: we rescue the content and rebuild it modern.' },
      { qEs: '¿Cuánto tarda?', qEn: 'How long does it take?', aEs: 'Normalmente una semana, porque el contenido ya existe.', aEn: 'Usually a week, since the content already exists.' },
    ],
  },
  {
    slug: 'reparacion-computadoras',
    slugEn: 'computer-repair',
    nombre: 'Reparación de equipos',
    name: 'Device repair',
    titleEs: 'Reparación de computadoras y teléfonos en El Progreso | Kizercode',
    titleEn: 'Computer and phone repair in El Progreso, Honduras | Kizercode',
    descEs: 'Reparación de computadoras y teléfonos en El Progreso, Yoro. Diagnóstico gratis: te decimos qué tiene y cuánto cuesta antes de tocar nada.',
    descEn: 'Computer and phone repair in El Progreso, Yoro. Free diagnosis: we tell you what it has and what it costs before touching anything.',
    h1Es: 'Reparación de computadoras y teléfonos, con diagnóstico gratis.',
    h1En: 'Computer and phone repair, with free diagnosis.',
    subEs: 'Te decimos qué tiene y cuánto cuesta, y vos aprobás antes de que toquemos nada. En El Progreso, Yoro. También compramos y vendemos equipo probado.',
    subEn: 'We tell you what it has and what it costs, and you approve before we touch anything. In El Progreso, Yoro. We also buy and sell tested equipment.',
    formServicio: 'Computer Repair',
    beneficios: [
      { tEs: 'Diagnóstico gratis', tEn: 'Free diagnosis', dEs: 'Saber qué tiene tu equipo no cuesta nada. Cobramos por arreglarlo.', dEn: 'Knowing what your device has costs nothing. We charge to fix it.' },
      { tEs: 'Vos aprobás primero', tEn: 'You approve first', dEs: 'Precio por escrito antes de abrir nada. Sin sorpresas al recoger.', dEn: 'Written price before opening anything. No surprises at pickup.' },
      { tEs: 'Entrega probada', tEn: 'Delivered tested', dEs: 'El equipo se va funcionando y con garantía sobre el arreglo.', dEn: 'The device leaves working, with warranty on the fix.' },
      { tEs: 'Compra y venta', tEn: 'Buy and sell', dEs: 'Recibimos tu equipo usado y vendemos equipo revisado y funcionando.', dEn: 'We take your used device and sell reviewed, working equipment.' },
    ],
    incluye: [
      { es: 'Pantallas, baterías y puertos', en: 'Screens, batteries and ports' },
      { es: 'Formateo, limpieza y mejoras (RAM/SSD)', en: 'Formatting, cleanup and upgrades (RAM/SSD)' },
      { es: 'Recuperación de datos cuando se puede', en: 'Data recovery when possible' },
      { es: 'Mantenimiento para negocios', en: 'Business maintenance plans' },
      { es: 'Compra y venta de equipo probado', en: 'Buy and sell of tested equipment' },
      { es: 'Garantía sobre el arreglo', en: 'Warranty on the repair' },
    ],
    faq: [
      { qEs: '¿Cuánto cuesta el diagnóstico?', qEn: 'How much is the diagnosis?', aEs: 'Nada. Te decimos qué tiene y cuánto costaría arreglarlo, y vos decidís.', aEn: 'Nothing. We tell you what it has and what fixing costs, and you decide.' },
      { qEs: '¿Cuánto tardan?', qEn: 'How long do repairs take?', aEs: 'Lo común (pantalla, batería, formateo) suele estar de un día para otro; si hay que pedir repuesto te avisamos de una.', aEn: 'Common fixes (screen, battery, formatting) are usually next-day; if a part must be ordered we tell you upfront.' },
      { qEs: '¿Mis archivos están seguros?', qEn: 'Are my files safe?', aEs: 'Sí. No tocamos tus datos sin avisarte, y si hay riesgo te lo decimos antes.', aEn: 'Yes. We never touch your data without telling you, and we flag any risk beforehand.' },
    ],
  },
];
